# remt-conda-forge.yml
name: remt
channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - python=3.11
  - pip
  # CLI bio tools
  - blast
  - diamond
  - hmmer=3.4
  - entrez-direct
  - ncbi-datasets-cli
  # Python bio libs
  - biopython
  - pyhmmer
  - pyrodigal
  # Py data stack (all from conda-forge)
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - umap-learn
  - matplotlib
  - seaborn
  - jupyterlab
  # misc utils
  - wget
  - curl
  # (optional) help the perl ecosystem stay consistent if needed:
  # - perl=5.32
  # - perl-json
  # - perl-json-xs<3